app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     
_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /admin/_console