security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern:            ^/backoffice
            form_login:
                provider:       fos_userbundle
                login_path:     app_back_office_security_login
                use_forward:    true
                use_referer:    true
                check_path:     app_back_office_security_check
                #failure_path:   null
                default_target_path: App_backofficebundle_home
            logout:
                path: app_back_office_security_logout
                target: app_main_homepage
            anonymous:   ~

        # defaut login area for standard users
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: true
            anonymous: ~ 
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: /mon-compte
                success_handler: user.security.authentication_handler
            oauth:
                resource_owners:
                    facebook:           "/connect/check-facebook"
                login_path:        /connect
                failure_path:      /connect
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
            logout:       true
            anonymous:    true

    access_control:
        - { path: '^/backoffice', roles: ROLE_ADMIN }
        - { path: '^/mon-compte', role: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/backoffice/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }