services:
    sonata.admin.skipper:
        class: AppBundle\Admin\SkipperAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Skipper" }
        arguments:
            - ~
            - AppBundle\Entity\Skipper
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [skipper]]
            - [ setBaseRoutePattern, [skipper]]
    sonata.admin.destination:
        class: AppBundle\Admin\DestinationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Destination" }
        arguments:
            - ~
            - AppBundle\Entity\Destination
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [destination]]
            - [ setBaseRoutePattern, [destination]]
    sonata.admin.portdepart:
        class: AppBundle\Admin\PortDepartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Port de départ" }
        arguments:
            - ~
            - AppBundle\Entity\PortDepart
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [portdepart]]
            - [ setBaseRoutePattern, [portdepart]]
    sonata.admin.itineraire:
        class: AppBundle\Admin\ItineraireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Itinéraire" }
        arguments:
            - ~
            - AppBundle\Entity\Itineraire
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [itineraire]]
            - [ setBaseRoutePattern, [itineraire]]
    sonata.admin.prestation:
        class: AppBundle\Admin\PrestationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Prestation" }
        arguments:
            - ~
            - AppBundle\Entity\Prestation
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [prestation]]
            - [ setBaseRoutePattern, [prestation]]
    sonata.admin.bateau:
        class: AppBundle\Admin\BateauAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bateau", label: "Bateau" }
        arguments:
            - ~
            - AppBundle\Entity\Bateau
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [bateau]]
            - [ setBaseRoutePattern, [bateau]]
    sonata.admin.inclusprix:
        class: AppBundle\Admin\InclusPrixAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bateau", label: "Inclus Prix" }
        arguments:
            - ~
            - AppBundle\Entity\InclusPrix
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [inclusprix]]
            - [ setBaseRoutePattern, [inclusprix]]
    sonata.admin.servicepayant:
        class: AppBundle\Admin\ServicePayantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bateau", label: "Services Payants" }
        arguments:
            - ~
            - AppBundle\Entity\ServicePayant
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [servicepayant]]
            - [ setBaseRoutePattern, [servicepayant]]
    sonata.admin.croisiere:
        class: AppBundle\Admin\CroisiereAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bateau", label: "Croisiere" }
        arguments:
            - ~
            - AppBundle\Entity\Croisiere
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [croisiere]]
            - [ setBaseRoutePattern, [croisiere]]
    sonata.admin.datenondisponibilite:
        class: AppBundle\Admin\DateNonDisponibiliteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Bateau", label: "Date non disponibilité", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\DateNonDisponibilite
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [datenondisponibilite]]
            - [ setBaseRoutePattern, [datenondisponibilite]]
