services:
    sonata.admin.skipper:
        class: AppBundle\Admin\SkipperAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Skipper" }
        arguments:
            - ~
            - AppBundle\Entity\Skipper
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [skipper]]
            - [ setBaseRoutePattern, [skipper]]
    sonata.admin.destination:
        class: AppBundle\Admin\DestinationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Destination" }
        arguments:
            - ~
            - AppBundle\Entity\Destination
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [destination]]
            - [ setBaseRoutePattern, [destination]]
    sonata.admin.portdepart:
        class: AppBundle\Admin\PortDepartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Port de départ" }
        arguments:
            - ~
            - AppBundle\Entity\PortDepart
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [portdepart]]
            - [ setBaseRoutePattern, [portdepart]]
    sonata.admin.itineraire:
        class: AppBundle\Admin\ItineraireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Itinéraire" }
        arguments:
            - ~
            - AppBundle\Entity\Itineraire
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [itineraire]]
            - [ setBaseRoutePattern, [itineraire]]
    sonata.admin.prestation:
        class: AppBundle\Admin\PrestationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Prestation" }
        arguments:
            - ~
            - AppBundle\Entity\Prestation
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [prestation]]
            - [ setBaseRoutePattern, [prestation]]
    sonata.admin.bateau:
        class: AppBundle\Admin\BateauAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Bateau" }
        arguments:
            - ~
            - AppBundle\Entity\Bateau
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [bateau]]
            - [ setBaseRoutePattern, [bateau]]
    sonata.admin.inclusprix:
        class: AppBundle\Admin\InclusPrixAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Inclus Prix" }
        arguments:
            - ~
            - AppBundle\Entity\InclusPrix
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [inclusprix]]
            - [ setBaseRoutePattern, [inclusprix]]
    sonata.admin.servicepayant:
        class: AppBundle\Admin\ServicePayantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Services Payants" }
        arguments:
            - ~
            - AppBundle\Entity\ServicePayant
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [servicepayant]]
            - [ setBaseRoutePattern, [servicepayant]]
    sonata.admin.croisiere:
        class: AppBundle\Admin\CroisiereAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Croisiere" }
        arguments:
            - ~
            - AppBundle\Entity\Croisiere
            - AppBundle:Croisiere
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [croisiere]]
            - [ setBaseRoutePattern, [croisiere]]
    sonata.admin.datenondisponibilite:
        class: AppBundle\Admin\DateNonDisponibiliteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Date non disponibilité", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\DateNonDisponibilite
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [datenondisponibilite]]
            - [ setBaseRoutePattern, [datenondisponibilite]]
    sonata.admin.tarifcroisiere:
        class: AppBundle\Admin\TarifCroisiereAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tarifs des croisières", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\TarifCroisiere
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [tarifcroisiere]]
            - [ setBaseRoutePattern, [tarifcroisiere]]
    sonata.admin.itinerairecroisiere:
        class: AppBundle\Admin\ItineraireCroisiereAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Itinéraires des croisières", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\ItineraireCroisiere
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [itinerairecroisiere]]
            - [ setBaseRoutePattern, [itinerairecroisiere]]
    sonata.admin.offrespeciale:
        class: AppBundle\Admin\OffreSpecialeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Offre spéciale" }
        arguments:
            - ~
            - AppBundle\Entity\OffreSpeciale
            - AppBundle:OffreSpecialeAdmin
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [offrespeciale]]
            - [ setBaseRoutePattern, [offrespeciale]]
    sonata.admin.devis:
        class: AppBundle\Admin\DevisAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Devis"}
        arguments:
            - ~
            - AppBundle\Entity\Devis
            - AppBundle:Devis
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [devis]]
            - [ setBaseRoutePattern, [devis]]