services:
    sonata.admin.skipper:
        class: AppBundle\Admin\SkipperAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Skipper" }
        arguments:
            - ~
            - AppBundle\Entity\Skipper
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ setBaseRouteName, [skipper]]
            - [ setBaseRoutePattern, [skipper]]