app_front_office_homepage:
    path:     /
    defaults: { _controller: AppFrontOfficeBundle:Default:index }

# SECURITY
app_front_office_security:
    resource: "@AppFrontOfficeBundle/Resources/config/routing/security.yml"
    
app_front_office_contract:
    path:     /contract
    defaults: { _controller: AppFrontOfficeBundle:Contract:index }