# SECURITY
app_back_office_security:
    resource: "@AppBackOfficeBundle/Resources/config/routing/security.yml"

# BACKOFFICE
app_back_office_bo:
    resource: "@AppBackOfficeBundle/Resources/config/routing/backoffice.yml"


app_back_office_category:
    resource: "@AppBackOfficeBundle/Resources/config/routing/category.yml"

app_back_office_provider:
    resource: "@AppBackOfficeBundle/Resources/config/routing/provider.yml"

app_back_office_cause_resiliation:
    resource: "@AppBackOfficeBundle/Resources/config/routing/cause_resiliation.yml"
    
