# SECURITY
app_back_office_security:
    resource: "@AppBackOfficeBundle/Resources/config/routing/security.yml"

# BACKOFFICE
app_back_office_bo:
    resource: "@AppBackOfficeBundle/Resources/config/routing/backoffice.yml"

# Category
app_back_office_category:
    resource: "@AppBackOfficeBundle/Resources/config/routing/category.yml"
# Provider
app_back_office_provider:
    resource: "@AppBackOfficeBundle/Resources/config/routing/provider.yml"
