app_main_homepage:
    path:     /
    defaults: { _controller: AppMainBundle:Default:index }

app_main_security:
    path:     /securite
    defaults: { _controller: AppMainBundle:Default:securite }

app_main_cgv:
    path:     /cgv
    defaults: { _controller: AppMainBundle:Default:cgv } 
    
app_main_contact:
    path:     /contact
    defaults: { _controller: AppMainBundle:Default:contact } 
    
app_main_contact_send:
    path:     /contact/send
    defaults: { _controller: AppMainBundle:Default:contactSend } 
       
# PROFILE
fos_user_profile_show:
    pattern: /profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        _method: GET

fos_user_profile_edit:
    pattern: /profile/editer
    defaults: { _controller: FOSUserBundle:Profile:edit }
    requirements:
        _method: GET|POST
        
check_login:
    pattern:  /check_login
    defaults: { _controller: AppMainBundle:Security:check }
    requirements:
        _method:  POST
    options:
        expose: true
        
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
# We override this part of the routing
hwi_oauth_connect: 
     resource: "@AppMainBundle/Resources/config/routing/connect.xml" 
     prefix: /connect
    
facebook_login:
    pattern: /connect/check-facebook