parameters:
#    app_front_office.example.class: App\FrontOfficeBundle\Example

services:
    user.form.profile.type:
        class: App\FrontOfficeBundle\Form\Type\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: app_fos_user_profile }
    user.form.register.type:
        class: App\MainBundle\Form\RegisterType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: app_fos_user_register }
    user.security.authentication_handler:
        class: App\MainBundle\Handler\AuthenticationHandler
        arguments: ['@router', '@session']
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    
