parameters:
#    app_front_office.example.class: App\FrontOfficeBundle\Example

services:
    user.form.profile.type:
        class: App\FrontOfficeBundle\Form\Type\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: app_fos_user_profile }
    user.form.register.type:
        class: App\MainBundle\Form\RegisterType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: app_fos_user_register }
    user.security.authentication_handler:
        class: App\MainBundle\Handler\AuthenticationHandler
        arguments: ['@router', '@session']
    app.oauth.user_provider:
        class: App\MainBundle\OAuth\UserProvider
        argumenty: ['fos_user.user_manager']
        tags:
            - { name: facebook, value: facebookId }
    
